pentatrion_vite:
    # Default build name (can be omitted if you only have one build)
    default_config: default
    configs:
        default:
            # Optional: Output configuration
            build_directory: 'build'
    # Public directory (defaults to 'public')
    public_directory: 'public'
    # Default configuration for the script tags
    script_attributes:
        type: 'module'
    # Default configuration for the style tags
    link_attributes: {}
    # If you use TypeScript and need to check your bundles
    throw_on_missing_entry: true
    # If you want to throw an exception when an asset is missing
    throw_on_missing_asset: true
    # Cache the manifest in production
    cache: '%kernel.debug%'
    # Preload assets
    preload: 'link-tag'
    # Set crossorigin attribute for preload tags
    crossorigin: 'anonymous'
    # Use absolute URLs
    absolute_url: '%kernel.debug%'
    # Proxy origin for development server
    proxy_origin: '%env(VITE_BASE_URL)%'
