security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: googleId

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: false
            custom_authenticators:
                - App\Security\JWTAuthenticator
            # Add session authentication
            provider: app_user_provider
            # Allow session authentication to work alongside JWT
            context: main
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\GoogleAuthenticator
            logout:
                path: app_logout
                target: connect_google
            access_denied_url: /login
            access_denied_handler: App\Security\AccessDeniedHandler

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/connect/google, roles: PUBLIC_ACCESS }
        - { path: ^/connect/google/check, roles: PUBLIC_ACCESS }
        # - { path: ^/app/callback, roles: PUBLIC_ACCESS } # Removed, no longer used
        - { path: ^/api/public, roles: PUBLIC_ACCESS }
        # - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS } # Removed: Must be protected by 'api' firewall
        - { path: ^/index, roles: PUBLIC_ACCESS }
        #- { path: ^/api, roles: ROLE_USER } # This now correctly covers /api/token/refresh
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        #- { path: ^/app, roles: ROLE_USER }
        - { path: ^/$, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
