.php-cache: &php-cache
    key:
        prefix: php
        files:
            - backend/composer.lock
    paths:
        - backend/vendor/
    policy: pull

.php-prod-cache: &php-prod-cache
    key:
        prefix: php-prod
        files:
            - backend/composer.lock
    paths:
        - backend/vendor/
    policy: pull

default:
    image: $CI_REGISTRY/sk/docker-php:8.4
    interruptible: true
    tags:
        - arm
        - small

stages:
    - install
    - test
    - deploy

variables:
    GIT_DEPTH: 0
    FF_USE_FASTZIP: 1
    CACHE_COMPRESSION_LEVEL: 'fastest'

workflow:
    rules:
        -   if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        -   if: $CI_COMMIT_BRANCH == 'master'
        -   if: $CI_COMMIT_TAG =~ /^prod-/

###
.install.php:
    stage: install
    rules:
        -   changes:
                - backend/composer.lock
        -   if: $CI_COMMIT_MESSAGE =~ /\[install\]/
    script:
        - cd backend
        - php composer.phar config -g cache-dir "$CI_PROJECT_DIR/.composer-cache"
        - php composer.phar install --prefer-dist --no-progress --no-interaction --no-scripts
    tags:
        - arm
        - large

install.php.ci:
    extends: .install.php
    cache:
        <<: *php-cache
        policy: push
    script:
        - cd backend
        - php composer.phar install --no-interaction --ansi

#install.php.prod:
#    extends: .install.php
#    cache:
#        <<: *php-prod-cache
#        policy: push
#    script:
#        - composer install --no-interaction --ansi --prefer-dist --optimize-autoloader

.test.php:
    stage: test
    cache:
        <<: *php-cache
    needs:
        -   job: install.php.ci
            optional: true
    before_script:
        - cd backend

#test.php.phpstan:
#    extends: .test.php
#    script:
#        - php -d memory_limit=512M vendor/bin/phpstan analyse src --level=1
#    tags:
#        - arm
#        - large

.deploy:
    stage: deploy
    image: $CI_REGISTRY/sk/docker-php-deployer:v7.3.3
    interruptible: false
    resource_group: deploy
    cache:
        <<: *php-prod-cache
    dependencies:
        #- build.admin
        #- build.frontend
    before_script:
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
        - cp "$DEPLOYMENT_KEY" ~/.ssh/id_ed25519
        - chmod 400 ~/.ssh/id_ed25519
        - cd backend

deploy.stage:
    extends: .deploy
    rules:
        - if: $CI_COMMIT_BRANCH == 'master'
    environment:
        name: stage
        url: https://chat-stage.www6.superkoderi.cz
    script:
        - cd backend
        #- 'printf "parameters:\n\tconfig:\n\t\twebVersion: \"%s\"" $CI_COMMIT_SHORT_SHA > app/config/webVersion.neon'
        - dep -f .deploy.php deploy


# deploy.production:
#     extends: .deploy
#     rules:
#         -   if: $CI_COMMIT_TAG =~ /^prod-/
#     environment:
#         name: production
#         url: https://chat-prod.www6.superkoderi.cz
#     script:
#         #- 'printf "parameters:\n\tconfig:\n\t\twebVersion: \"%s\"" $CI_COMMIT_SHORT_SHA > app/config/webVersion.neon'
#         - dep -f .deploy.php deploy