version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
      - ./.env.local:/var/www/html/.env.local:ro
    depends_on:
      - database
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_URL=http://localhost:8000
      - VITE_BASE_URL=http://localhost:5173
      - DATABASE_URL=mysql://app:!ChangeMe!@database:3306/app?serverVersion=8.0
    env_file:
      - .env.local
    networks:
      - app-network

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - ./.env.local:/app/.env.local:ro
    working_dir: /app
    command: npm run dev
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_URL=http://localhost:5173
    env_file:
      - .env.local
    networks:
      - app-network

  database:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=!ChangeMe!
      - MYSQL_ROOT_PASSWORD=!ChangeMe!
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
